// f:\Zapplogics\Tasks\math_345_duplicate\short_extensions\lib\src\functions.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'animateScrollToEnd.dart';
export 'createFadeTransitionRoute.dart';
export 'createRandomUniqueList.dart';
export 'createSlideTransitionRoute.dart';
export 'dismissKeyboard.dart';
export 'displayAndSelectDate.dart';
export 'goToScreen.dart';
export 'goToWithTransitionToScreen.dart';
export 'incrementByValue.dart';
export 'isEmailValid.dart';
export 'isPhoneNumberValid.dart';
export 'moveCursorToTextEnd.dart';
export 'NotificationBar.dart';
export 'placeCursorAtTextEnd.dart';
export 'printLog.dart';
export 'reduceValueToZero.dart';
export 'setOrientation.dart';