// f:\Zapplogics\Tasks\math_345_duplicate\short_extensions\lib\src\dialogs.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'account_deletion_confirmation_dialog.dart';
export 'delete_message_dialog.dart';
export 'showExitDialog.dart';
export 'showGeneralMessageDialogWithbuttons.dart';
export 'showLoginRequiredDialog.dart';
export 'showNoInternetDialog.dart';
export 'showOkDialog.dart';
export 'yesnoAlertDialog.dart';